### ISSUE TITLE
error

### ISSUE THREAD

**Issue by JonhSilver** [Plazmaz/Sublist3r#5]
c:\python27>python.exe sub2/sub.py -d site.com
[!] Error: Coloring libraries not installed ,no coloring will be used [Check the
 readme]
←[91m
                     ____        _     _ _     _   _____
                    / ___| _   _| |__ | (_)___| |_|___ / _ __
                    \___ \| | | | '_ \| | / __| __| |_ \| '__|
                     ___) | |_| | |_) | | \__ \ |_ ___) | |
                    |____/ \__,_|_.__/|_|_|___/\__|____/|_|←[0m←[93m

                    # Coded By Ahmed Aboul-Ela - @aboul3la

←[94m[-] Enumerating subdomains now for site.com←[0m
←[92m[-] Searching now in Baidu..←[0m
Traceback (most recent call last):
  File "sub2/sub.py", line 82, in <module>
    takeover_check=takeover_check, engines=engines)
  File "sub2/sub.py", line 63, in main
    return scanner.scan()
  File "c:\python27\sub2\subscann3r.py", line 86, in scan
    enums = [enum(self.domain, [], q=subdomains_queue, silent=self.scan_flags.Si
lent, logger=self.logger) for enum in chosenEnums]
  File "c:\python27\sub2\engines\engine.py", line 244, in __init__
    logger=logger)
  File "c:\python27\sub2\engines\engine.py", line 32, in __init__
    multiprocessing.Process.__init__(self)
TypeError: unbound method __init__() must be called with Thread instance as firs
t argument (got BaiduEnum instance instead)

**Comment by Plazmaz** [comment]
Hmm I can't reproduce this. Can you tell me what OS and version of python you're using?
EDIT:  It looks like you're using Windows. Currently I haven't thoroughly tested this tool with barebones windows. I generally run it with Bash on Ubuntu on Windows. I suggest using that or another similar environment, such as git bash, linux, or OSX.

**Comment by Plazmaz** [comment]
Regardless, I'll look into this.

**Comment by Plazmaz** [comment]
This looks like an issue with python 3. When you get a chance, the version of python you're using would be helpful

**Comment by JonhSilver** [comment]
Windows server 2012 r2
python 2.7.6

**Comment by Plazmaz** [comment]
@JonhSilver weird. I can't reproduce this on 2.7.6. It looks like you've renamed some of the files(`sub.py`). Could you try with a fresh clone of the repo?

**Comment by JonhSilver** [comment]
nope, the same error on fresh clone too

c:\python27>python.exe Sublist3r-master/sublist3r.py --domain site.com
[!] Error: Coloring libraries not installed ,no coloring will be used [Check the
 readme]
←[91m
                     ____        _     _ _     _   _____
                    / ___| _   _| |__ | (_)___| |_|___ / _ __
                    \___ \| | | | '_ \| | / __| __| |_ \| '__|
                     ___) | |_| | |_) | | \__ \ |_ ___) | |
                    |____/ \__,_|_.__/|_|_|___/\__|____/|_|←[0m←[93m

                    # Coded By Ahmed Aboul-Ela - @aboul3la
                    # Rewritten by Dylan Katz  - @Plazmaz

←[94m[-] Enumerating subdomains now for site.com←[0m
←[92m[-] Searching now in Baidu..←[0m
Traceback (most recent call last):
  File "Sublist3r-master/sublist3r.py", line 83, in <module>
    takeover_check=takeover_check, engines=engines)
  File "Sublist3r-master/sublist3r.py", line 64, in main
    return scanner.scan()
  File "c:\python27\Sublist3r-master\subscann3r.py", line 86, in scan
    enums = [enum(self.domain, [], q=subdomains_queue, silent=self.scan_flags.Si
lent, logger=self.logger) for enum in chosenEnums]
  File "c:\python27\Sublist3r-master\engines\engine.py", line 243, in __init__
    EnumratorBaseThreaded.__init__(self, base_url, self.engine_name, domain, sub
domains, q=q, silent=silent, logger=logger)
  File "c:\python27\Sublist3r-master\engines\engine.py", line 32, in __init__
    multiprocessing.Process.__init__(self)
TypeError: unbound method __init__() must be called with Thread instance as firs
t argument (got BaiduEnum instance instead)

**Comment by JonhSilver** [comment]
Something wrong with threads.
On others windows PCs same error, on newest python version too.
2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]

**Comment by Plazmaz** [comment]
@JonhSilver It's likely that python 3 will completely resolve this issue for you. In the long run, I'll work on a fix, but it may be a bit. I'm able to reproduce it, so I can probably fix it.

**Comment by Plazmaz** [comment]
@JonhSilver this should be fixed now. Please let me know if there's still issues :)
