### ISSUE TITLE
ip option -i

### ISSUE THREAD

**Issue by jhaddix** [Plazmaz/Sublist3r#7]
Hey @Plazmaz can you grab this feature here and merge? it's super useful for large scoped projects:

``` https://github.com/aboul3la/Sublist3r/pull/107 ```

**Comment by Plazmaz** [comment]
Hi @jhaddix. If you want that feature here, I strongly suggest talking to the PR author and having them PR to this repo, as the codebase here is pretty difficult to merge with stuff made for the other codebase. This is close to a complete restructuring of the original project, and I really don't have time to be actively writing code for this repo(although I will continue to merge PRs and respond to issues).
Thanks!

**Comment by jhaddix** [comment]
Makes sense, sad though since the original author is MIA. It is a great tool. Maybe I will just port all these modules back to recon-ng.

**Comment by Plazmaz** [comment]
@jhaddix Just so you know, that was in no way me saying I've abandoned this project. Even though I'm not writing much code for it, it will continue to exist and I will continue to respond to PRs and issues.

**Comment by jhaddix** [comment]
Thanks for the hard work =)
